In [1]:
import numpy as np

list_ = [ 1,2,3,4,5 ]

array_list = np.array(object = list_)

In [2]:
"""
Q1. Is there any difference in the data type of variables list_ and array_list? 
If there is then write a code to print the data types of both the variables.
"""

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


In [3]:
"""
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.
"""

for i in list_:
    print(type(i))
    
for i in array_list:
    print(type(i))

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [6]:
"""
Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

"""
array_list = np.array(object = list_, dtype = int)

for i in list_:
    print(type(i))
    
for i in array_list:
    print(type(i))

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

for i in num_list:
    print(type(i))
    
for i in num_array:
    print(type(i))


<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'list'>
<class 'list'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
"""
Q4. Write a code to find the following characteristics of variable, num_array:

(i) shape

(ii) size

"""

num_array = np.array([[1, 2, 3], [4, 5, 6]])
shape = num_array.shape
print("Shape:", shape)
size = num_array.size
print("Size:", size)

Shape: (2, 3)
Size: 6


In [8]:
"""
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]
"""

l=np.zeros((3,3))
l

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
"""
Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]
"""

identity_matrix = np.eye(5)
print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
